CREATE DATABASE CLIENTEMANAGER
GO

USE CLIENTEMANAGER
GO

CREATE TABLE T_CLIENTE (
    Id INT PRIMARY KEY IDENTITY(1,1),
    CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    DATA_EXPEDICAO DATETIME NOT NULL,
    ORGAO_EXPEDICAO VARCHAR(50) NOT NULL,
    UF_ORGAO CHAR(2) NOT NULL,
    DATA_NASCIMENTO DATETIME NOT NULL,
    SEXO CHAR(1) NOT NULL,
    ESTADO_CIVIL VARCHAR(20) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    LOGRADOURO VARCHAR(200) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(100),
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    UF_ENDERECO CHAR(2) NOT NULL 
);
GO